language: python
python:
    - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/AerisForecastsDemo
    - PLATFORMIO_CI_SRC=examples/AerisObservationDemo
    - PLATFORMIO_CI_SRC=examples/AerisSunMoonDemo
    - PLATFORMIO_CI_SRC=examples/AstronomyDemo
    - PLATFORMIO_CI_SRC=examples/OpenWeatherMapCurrentDemo
    - PLATFORMIO_CI_SRC=examples/OpenWeatherMapForecastDemo
    - PLATFORMIO_CI_SRC=examples/PlaneSpotterDemo
    - PLATFORMIO_CI_SRC=examples/SunMoonCalcDemo
    - PLATFORMIO_CI_SRC=examples/WeatherStationDemo
    - PLATFORMIO_CI_SRC=examples/WorldClockDemo

install:
    - pip install -U platformio
    - platformio lib -g install "JsonStreamingParser" "squix78/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.2.0" "WifiManager@>=0.15.0-beta" "simpleDSTadjust" "Adafruit Unified Sensor" "DHT sensor library"
    - platformio lib update

script:
    - platformio ci --lib="." --project-option="lib_deps=JsonStreamingParser" --board=nodemcuv2
